---
- name: Provision an EC2 Instance
  hosts: localhost
  tags: provisioning
  
  roles:
    - ec2
    
  vars:
    # Here are variables related to the Tomcat installation
    http_port: 8080
    https_port: 8443
    # This will configure a default manager-gui user:
    admin_username: admin
    admin_password: admin123  
    firewalld_state: latest
    firewall_debug: true
    firewalld_rules:
      ssh:
        port: 22
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      http:
        port: 80
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      https:
        port: 443
        protocol: tcp
        state: enabled
        zone: public
        permanent: true

- name: install tomcat
  hosts: ec2hosts
  gather_facts: True
  become: yes
  become_method: sudo

  roles:
    - firewalld
    - selinux
    - tomcat 
